[package]
name = "tokio-process-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["signal", "process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Console"] }

[dev-dependencies]
tempfile = "3.12.0"
