[package]
name = "tokio-process-tools"
version = "0.7.1"
edition = "2024"
rust-version = "1.85.0"
repository = "https://github.com/lpotthast/tokio-process-tools"
description = """
Interact with processes spawned by tokio.
"""
categories = ["asynchronous", "concurrency"]
keywords = ["tokio", "process", "management", "collector"]
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]

[dependencies]
atomic-take = "1.1.0"
bytes = { version = "1.10.1", default-features = false, features = ["std"] }
thiserror = { version = "2.0.17", default-features = false, features = ["std"] }
tokio = { version = "1.48.0", default-features = false, features = ["process", "sync", "io-util", "macros", "rt-multi-thread", "time"] }
tracing = { version = "0.1.41", default-features = false, features = ["std"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", default-features = false, features = ["signal", "process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", default-features = false, features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Console"] }

[dev-dependencies]
assertr = "0.4.0"
jiff = "0.2.15"
mockall = "0.13.1"
tempfile = "3.23.0"
tokio = { version = "1.48.0", features = ["fs"] }
tokio-test = "0.4.4"
tracing-test = "0.2.5"
