[package]
name = "tokio-process-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"

[dev-dependencies]
tempfile = "3.12.0"
