[package]
name = "tokio-process-tools"
version = "0.5.0"
edition = "2024"
rust-version = "1.85.0"
repository = "https://github.com/lpotthast/tokio-process-tools"
description = """
Interact with processes spawned by tokio.
"""
categories = ["asynchronous", "concurrency"]
keywords = ["tokio", "process", "management", "collector"]
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]

[dependencies]
bytes = "1.10.1"
thiserror = "2.0.10"
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", features = ["signal", "process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Console"] }

[dev-dependencies]
assertr = "0.3.0"
tempfile = "3.15.0"
mockall = "0.13.1"
tracing-test = "0.2.5"
jiff = "0.2.13"
