[package]
name = "tokio-process-tools"
version = "0.1.1"
edition = "2021"
rust-version = "1.78.0"
repository = "https://github.com/lpotthast/tokio-process-tools"
description = """
Interact with processes spawned by tokio.
"""
categories = ["asynchronous", "concurrency"]
keywords = ["tokio", "process", "management", "collector"]
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]

[dependencies]
thiserror = "2.0.10"
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["signal", "process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Console"] }

[dev-dependencies]
tempfile = "3.12.0"
mockall = "0.13.1"
